### PR TITLE
Backspace now deletes up to tab_size spaces

### LINKED ISSUE #716: backspace with translate_tabs_to_spaces should delete up to tab_width preceding spaces
This was previously implemented (in #460) but broke somewhere along the way. That PR contains a good discussion of the motivation and ultimate design. Care should be taken not to regress on #714/#713. I'd like this to also include a test case in `event_context.rs`; doing this correctly might involve modifying the `ContextHarness` used for testing to allow it to be passed a custom config, which wasn't possible when that was first written.

As a bonus it would be great to also have a regression test for #713.

### PR DESCRIPTION
**Pull request by nangtrongvuon**
This is an attempt to fix #716. 

Backspace should now have correct behavior, which is deleting up to config.tab_size at a time for each backspace press. Care was also taken not to regress #713/#714.

### CODE REVIEW

File: rust/core-lib/src/editor.rs [hunk 1]
```diff
@@ -345,22 +345,31 @@ impl Editor {
                 // backspace deletes max(1, tab_size) contiguous spaces
                 let (_, c) = view.offset_to_line_col(&self.text, region.start);
 
-                let tab_off = c & config.tab_size;
+                // Offset of cursor position from nearest tab
+                let tab_off = c % config.tab_size;
```
Comment (cmyr) [inline rust/core-lib/src/editor.rs]: I think this change alone is the fix?? I have no idea how this was a `&` before, I think it must've been a typo. Changing this to a `%` should enough?

File: rust/core-lib/src/editor.rs [hunk 2]
```diff
@@ -345,22 +345,31 @@ impl Editor {
...
                 let tab_size = config.tab_size;
-                let tab_size = if tab_off == 0 { tab_size } else { tab_off };
+
+                // Size of tab, counted from cursor to nearest tab
+                let tab_size = if tab_off == 0 { if c > tab_off { tab_size } else { c - tab_off } } else { tab_off };
                 let tab_start = region.start.saturating_sub(tab_size);
-                let preceded_by_spaces = region.start > 0 &&
-                    (tab_start..region.start).all(|i| self.text.byte_at(i) == b' ');
+                let preceded_by_spaces = region.start > 0 && tab_size > 0
+                && self.text.slice_to_string(tab_start, region.start).chars().all(|i| i.is_whitespace());
```
Comment (cmyr) [inline rust/core-lib/src/editor.rs]: I'm not sure about this change; among other things it now means that if tab_size is 4 this will delete three tabs and a space on backspace. In addition it requires us to allocate a string, instead of doing the comparison in the existing buffer.

**Comment by nangtrongvuon** [comment]
You're right, I definitely came to the same original algorithm, which is checking where the tab starts. The "&" sign definitely threw me off.

I reduced the fix to just that, and I think it works as expected now!
