### PR TITLE
Fix broken delta predicates

### LINKED ISSUE #507: crash in rust plugin lib when pasting over a selection
This is a regression in #481. 

Repro:
1. Copy some text to the clipboard
2. select some amount of text shorter than what is in your clipboard
3. paste

backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /Users/rofls/dev/projects/xi-mac/xi-editor/rust/plugin-lib/src/state_cache.rs:526:12
stack backtrace:
   0:        0x1002d2ca3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h3421d74c3554d1d6
   1:        0x1002cf64c - std::sys_common::backtrace::_print::h81d2920454574615
   2:        0x1002d4ad1 - std::panicking::default_hook::{{closure}}::h046b82ccd70886b8
   3:        0x1002d47d6 - std::panicking::default_hook::h00ff9adc172e30f9
   4:        0x1002d5015 - std::panicking::rust_panic_with_hook::hb58bab85cf8f73f4
   5:        0x1002d4eae - std::panicking::begin_panic::hf76e4af07ba1dfa4
   6:        0x1002d4d82 - std::panicking::begin_panic_fmt::hf59ff9d53a059895
   7:        0x10009668d - <xi_plugin_lib::state_cache::PluginCtx<'a, S>>::update_line_cache::ha8ce6fc05aba9900
   8:        0x10009856d - <xi_plugin_lib::state_cache::PluginCtx<'a, S>>::do_update::hb81e3c7f1aefeaf9
   9:        0x1000814b1 - <xi_plugin_lib::state_cache::CacheHandler<'a, P> as xi_plugin_lib::plugin_base::Handler>::handle_request::he20fa1e6d4ff94de
  10:        0x100102bfe - <xi_plugin_lib::plugin_base::MyHandler<'a, H> as xi_rpc::Handler>::handle_request::hde6c4a9d85f57650
  11:        0x100079329 - <xi_rpc::RpcLoop<W>>::mainloop::{{closure}}::h9fa2ce7a2e01d170
  12:        0x10009f0db - crossbeam::scoped::scope::h9e09d4ee80ac304d
  13:        0x100078d2c - <xi_rpc::RpcLoop<W>>::mainloop::he4d9c5576edc92fe
  14:        0x1000f21cd - xi_plugin_lib::plugin_base::mainloop::hba368e66445bc3d0
  15:        0x100081b71 - xi_plugin_lib::state_cache::mainloop::h38e1e5059b7022b3
  16:        0x10016749b - xi_syntect_plugin::main::h60797c0ffaed0b80
  17:        0x1002dfdfe - __rust_maybe_catch_panic
  18:        0x1002d52d8 - std::rt::lang_start::h0ff358a55ab2ec4c
  19:        0x100167534 - main
```

This is interesting, because it means that the behaviour of `Delta::iter_deletions` doesn't match my intuition; I would expect in this case for it to return a span. I'm not sure if that's a bug or a documentation problem.

One work around might be to check the length of the interval returned by `self.summary()` in `Delta::as_simple_insert`, and return `None` in that case, but that feels inelegant. 😕

### PR DESCRIPTION
**Pull request by raphlinus**
The delta predicates (is_simple_delete and as_simple_insert) didn't
handle all cases correctly, especially mixed inserts and delets. This
patch reimplements them from scratch.

Fixes #507

### CODE REVIEW

File: rust/rope/src/delta.rs [hunk 1]
```diff
@@ -63,20 +63,55 @@ impl<N: NodeInfo> Delta<N> {
...
+                    return Some(n);
                 }
             }
         }
         None
     }
 
     /// Returns `true` if this delta represents a single deletion without
-    /// any insertions.
+    /// any insertions. Note that this is `false` for the trivial delta.
```
Comment (cmyr) [inline rust/rope/src/delta.rs]: The trivial delta has no `el`s and zero `base_len`?

File: rust/rope/src/delta.rs [hunk 2]
```diff
@@ -63,20 +63,55 @@ impl<N: NodeInfo> Delta<N> {
...
     pub fn is_simple_delete(&self) -> bool {
-        self.els.len() <= 2 && self.iter_inserts().count() == 0
+        if self.els.is_empty() && self.base_len > 0 {
+            return true;
+        }
+        if let DeltaElement::Copy(beg, end) = self.els[0] {
+            if beg == 0 {
+                if self.els.len() == 1 {
+                    // Deletion at end
+                    end < self.base_len
```
Comment (cmyr) [inline rust/rope/src/delta.rs]: isn't this an invariant?

File: rust/rope/src/delta.rs (hunk 1 above)
Comment (raphlinus) [reply rust/rope/src/delta.rs]: Not quite. If base_len is 0, then it is empty, otherwise it is a copy from 0..base_len.

File: rust/rope/src/delta.rs (hunk 2 above)
Comment (raphlinus) [reply rust/rope/src/delta.rs]: See above, not if the delta is trivial and base_len is nonzero.
