### PR TITLE
Fix #352

### LINKED ISSUE #352: syntect plugin is missing spans
With syntect enabled, some text regions are missing spans. I’m not sure yet if this is a regression: to be visible it requires using a theme where the normal text color is distinct from the system default text color.

In xi-mac, text with no associated spans is drawn using the default foreground color by default, so this isn’t especially visual. When I disable that, and draw unstyled text in another color, it looks like this:

(to reproduce these screenshots, comment out the line `attributes[NSForegroundColorAttributeName] = textColor` in `TextDrawingMetrics` in `EditView.swift`, line 55 as of this writing.)

screen shot 2017-06-30 at 9 56 08 am
screen shot 2017-06-30 at 9 56 17 am
screen shot 2017-06-30 at 10 01 12 am

### PR DESCRIPTION
**Pull request by cmyr**
While we were correctly calculating the stack state at EOL, we were not
generating a style span for the last state in each line.

### CODE REVIEW

File: rust/syntect-plugin/src/stackmap.rs [hunk 1]
```diff
@@ -10,7 +10,6 @@
 // distributed under the License is distributed on an "AS IS" BASIS,
 // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 // See the License for the specific language governing permissions and
-// limitations under the License.
```
Comment (raphlinus) [inline rust/syntect-plugin/src/stackmap.rs]: Pretty sure this wasn't intentional.

Comment (cmyr) [reply rust/syntect-plugin/src/stackmap.rs]: 😁 rups
